[package]
name = "eth_marketplace_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
[dependencies]
ethers = { version = "1.0", features = ["contract", "rustls"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
dotenv = "0.15"
